title: "Shixian Liu"
description: "Personal academic website on thermophysics and phonon transport"
url: "https://sxliu.site"
baseurl: ""
lang: en
timezone: Europe/Moscow
markdown: kramdown

author:
  name: "Shixian Liu"
  url: "https://sxliu.site"
  links:
    - "https://scholar.google.com/citations?user=bLVSRuUAAAAJ"
    - "https://orcid.org/0000-0003-3042-7817"
    - "https://github.com/lyushisyan"

social:
  name: "Shixian Liu"
  links:
    - "https://scholar.google.com/citations?user=bLVSRuUAAAAJ"
    - "https://orcid.org/0000-0003-3042-7817"
    - "https://github.com/lyushisyan"

logo: "/assets/img/profile/favicon.png"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed
  sass_dir: _sass
permalink: /blog/:year/:month/:day/:title/

nav:
  - title: About
    url: /about/
  - title: News
    url: /news/
  - title: Blog
    url: /blog/
  - title: Publications
    url: /publications/
  - title: Software
    url: /software/
  - title: Teaching
    url: /teaching/

defaults:
  - scope:
      path: "_posts/zh"
      type: "posts"
    values:
      lang: zh
      permalink: /zh/blog/:year/:month/:day/:title/
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      math: true
  - scope:
      path: ""
    values:
      layout: page
